- include: task_rollout.yml
  tags: rollout
  when: >
    drupal_task_name == 'rollout'
    and (instance.name == drupal_task_instance or drupal_task_instance == '')

- include: task_cron.yml
  tags: cron
  when: >
    drupal_task_name == 'cron'
    and (instance.name == drupal_task_instance or drupal_task_instance == '')

- include: task_scheduler.yml
  tags: scheduler
  when: >
    drupal_task_name == 'scheduler'
    and (instance.name == drupal_task_instance or drupal_task_instance == '')
