- include: task_rollout.yml
  tags: rollout
  when: drupal_task_name == 'rollout'

- include: task_cron.yml
  tags: cron
  when: drupal_task_name == 'cron'

- include: task_scheduler.yml
  tags: scheduler
  when: drupal_task_name == 'scheduler'
