- fail:
    msg: 'drupal_task_name variable has to be set with --extra-vars "drupal_task_name=rollout"'
  when: drupal_task_name == ''

- include_tasks: instance.yml
  loop: '{{ drupal_instances | default([])}}'
  loop_control:
    loop_var: instance
  tags: drupal
