- set_fact: rollout_with_updatedb="{{ instance.rollout_with_updatedb | default(drupal_rollout_with_updatedb) }}"
- set_fact: rollout_with_entity_updates="{{ instance.rollout_with_entity_updates | default(drupal_rollout_with_entity_updates) }}"
- set_fact: rollout_with_cron="{{ instance.rollout_with_cron | default(drupal_rollout_with_cron) }}"
- set_fact: rollout_with_cache_clear="{{ instance.rollout_with_cache_clear | default(drupal_rollout_with_cache_clear) }}"
- set_fact: rollout_with_cim="{{ instance.rollout_with_cim | default(drupal_rollout_with_cim) }}"

- name: Run git clone/pull - {{ instance.name }}
  git:
    repo: '{{ instance.repo }}'
    dest: '{{ instance.dir }}'
    version: '{{ instance.repo_version | default(omit) }}'
    accept_hostkey: true
  register: git_result

- block:
  - name: Run composer update - {{ instance.name }}
    command: 'composer update'
    args:
      chdir: "{{ instance.dir }}{{ instance.vhost_dir | default('/htdocs') }}"
    register: composer_result
    changed_when: composer_result.rc != 0

  - name: Output of composer update - {{ instance.name }}
    debug: var=composer_result.stdout_lines
    when: composer_result.stdout_lines | length

  when: >
    instance.with_composer_update is defined
    and instance.with_composer_update

- block:
  - name: Run updatedb - {{ instance.name }}
    command: '{{ drush_path }} @{{ instance.name }} --yes updatedb'
    register: update_result
    changed_when: update_result.rc != 0

  - name: Output of updatedb - {{ instance.name }}
    debug: var=update_result.stdout_lines
    when: update_result.stdout_lines | length

  when: >
    rollout_with_updatedb
    and (mysql_replication_role is undefined or mysql_replication_role == 'master')
    and sync_master is undefined

- block:
  - name: Run entity-updates - {{ instance.name }}
    command: '{{ drush_path }} @{{ instance.name }} --yes entity-updates'
    register: entity_result
    changed_when: entity_result.rc != 0

  - name: Output of entity-updates - {{ instance.name }}
    debug: var=entity_result.stdout_lines
    when: entity_result.stdout_lines | length

  when: >
    rollout_with_entity_updates
    and (mysql_replication_role is undefined or mysql_replication_role == 'master')
    and sync_master is undefined

- include_tasks: rollout_drupal7.yml
  tags: drupal7
  when: instance.major_version is undefined or instance.major_version == 7

- include_tasks: rollout_drupal8.yml
  tags: drupal8
  when: instance.major_version is defined and instance.major_version == 8

- block:
  - name: Run cron - {{ instance.name }}
    command: '{{ drush_path }} @{{ instance.name }} cron'
    register: cron_result
    ignore_errors: yes

  - name: Output of cron - {{ instance.name }}
    debug: var=cron_result.stdout_lines
    when: cron_result.stdout_lines | length

  when: >
    rollout_with_cron
    and (mysql_replication_role is undefined or mysql_replication_role == 'master')
    and sync_master is undefined
