- name: Run drupal scheduler - light-weight cron (drush) - {{ instance.name }}
  become: '{{ true if drupal_user is defined else false }}'
  become_user: '{{ drupal_user | default(omit) }}'
  command: '{{ drush_path }} @{{ instance.name }} scheduler-cron'
  when: >
    (mysql_replication_role is undefined or mysql_replication_role == 'master')
    and sync_master is undefined
